### ISSUE TITLE
Default file is not specified

### ISSUE THREAD

**Issue by Klaudioz** [usernamehw/vscode-todo-md#13]
I have an existent `todo.md`. If I run: Todo MD: Add a task I get:

`Default file is not specified` even when it was specified.

![image](https://user-images.githubusercontent.com/632625/95760701-93c18f00-0c68-11eb-953c-ba9790cd96b2.png)
![image](https://user-images.githubusercontent.com/632625/95760756-a63bc880-0c68-11eb-9b00-758e1d08130c.png)

The same happens with Todo MD: Open default archive file.

Using MacOS Catalina 10.15.6

**Comment by usernamehw** [comment]
Sadly, I don't have a MacOS machine to test it. Can you reproduce after editor reload?

Is the message says `Default file is not specified.` or `Default file does not exist.`? Because `not specified` should only be shown  when the  path is empty.

Any other messages in the console: `Developer: Toggle Developer Tools`?

**Comment by Klaudioz** [comment]
Thanks for your reply. Everything worked after restart VSCode.
