### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by zillionare** [usernamehw/vscode-todo-md#15]
1.  Support nested tasks. After this has been implemented, actually ``+project`` can be retired. Currently I have to manually mark almost every task with proper 'project', hope using nested task can save us a lot of time.
2. Support due on hours/minutes grain. Currently only day level is supported
3. block comments support and auto-hide
4. reminder according to task due
5. documentation on why and how to use context, project, tags

**Comment by usernamehw** [comment]
1. No plans on retiring projects
2. Created https://github.com/usernamehw/vscode-todo-md/issues/16
3. Created https://github.com/usernamehw/vscode-todo-md/issues/17
4. Created https://github.com/usernamehw/vscode-todo-md/issues/18
5. I don't even know when to use what. They might be used differently depending on a person.

Created issues since 1 idea - 1 issue is a good rule. No work is planned since I have no spare time.
